options:
  scheme:
    type: string
    default: "internet-facing"
    description: |
      Scheme to use for loadbalancer, 'internet-facing' or 'internal'.
      Defaults to 'internet-facing'.
  cert-fqdn:
    type: string
    default: ""
    description: |
      FQDN matching the iregex for the cert you wish to use in ACM.
  subnets:
    type: string
    default: ""
    description: |
      Comma separated list of subnet-ids to use for ELB provisioning.
      
